name: Docker Build and Push
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      release_type:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      release_type:
        required: true
        type: choice
        options:
          - base
          - main
env:
  POETRY_VERSION: "1.8.2"
  TEST_TAG: "langflowai/langflow:test"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.set-vars.outputs.tags }}
      file: ${{ steps.set-vars.outputs.file }}
    steps:
      - uses: actions/checkout@v4
      - name: Set Dockerfile and Tags
        id: set-vars
        run: |
          if [[ "${{ inputs.release_type }}" == "base" ]]; then
            echo "tags=langflowai/langflow:base-${{ inputs.version }}" >> $GITHUB_OUTPUT
            echo "file=./docker/build_and_push_base.Dockerfile" >> $GITHUB_OUTPUT
          else
            echo "tags=langflowai/langflow:${{ inputs.version }},langflowai/langflow:1.0-alpha" >> $GITHUB_OUTPUT
            echo "file=./docker/build_and_push.Dockerfile" >> $GITHUB_OUTPUT
          fi
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build Docker Image
      #   uses: docker/build-push-action@v5
      #   id: docker_build
      #   with:
      #     context: .
      #     push: false  # Do not push yet
      #     platforms: "linux/amd64,linux/arm64/v8"
      #     load: true
      #     file: ${{ matrix.file }}
      #     tags: ${{ env.TEST_TAG }}
      # - name: Run Container
      #   run: |
      #     docker run -d --name test_container -p 8000:8000 ${{ needs.setup.outputs.tags }}
      # - name: Wait for Container to Start and Check Health
      #   run: |
      #     timeout 40 bash -c 'until curl -f http://127.0.0.1:8000/health; do sleep 1; done' || (echo "Server did not start in time" && docker logs test_container && docker stop test_container && docker rm test_container && exit 1)
      # - name: Stop and Remove Container
      #   run: |
      #     docker stop test_container
      #     docker rm test_container
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: "linux/amd64"
          file: ${{ needs.setup.outputs.file }}
          tags: ${{ needs.setup.outputs.tags }}

  build_components:
    if: ${{ inputs.release_type == 'main' }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        component: [backend, frontend]
        include:
          - component: backend
            dockerfile: ./docker/build_and_push_backend.Dockerfile
            tags: langflowai/langflow-backend:${{ inputs.version }},langflowai/langflow-backend:1.0-alpha
          - component: frontend
            dockerfile: ./docker/frontend/build_and_push_frontend.Dockerfile
            tags: langflowai/langflow-frontend:${{ inputs.version }},langflowai/langflow-frontend:1.0-alpha
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Wait for Docker Hub to propagate (for backend)
        run: sleep 120
      - name: Build and push ${{ matrix.component }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: "linux/amd64"
          build-args: |
            LANGFLOW_IMAGE=langflowai/langflow:${{ inputs.version }}
          file: ${{ matrix.dockerfile }}
          tags: ${{ matrix.tags }}

  restart-space:
    name: Restart HuggingFace Spaces
    if: ${{ inputs.release_type == 'main' }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_caching"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          cache-key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Python dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install

      - name: Restart HuggingFace Spaces Build
        run: |
          poetry run python ./scripts/factory_restart_space.py --space "Langflow/Langflow-Preview" --token ${{ secrets.HUGGINGFACE_API_TOKEN }}
